name = "invoice-summeriser"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
# pages_build_output_dir = ".next"

# Bind Cloudflare AI (Free tier)
[ai]
binding = "AI"

# Bind Cloudflare D1 SQL Database for Alerts (Free tier)
[[d1_databases]]
binding = "DB"
database_name = "iv-saas-alerts-db"
database_id = "9a69a62a-863b-4906-b09c-952804eb107d"